alias: list telegram commands
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/list'
action:
  - service: telegram_bot.send_message
    data:
      message: 'Here are all available commands:'
      inline_keyboard:
        - 'vacuum:/vacuum'
        - 'hass:/hass'
