alias: list telegram commands
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/list'
action:
  - service: telegram_bot.send_message
    data:
      message: !include command_list_message.yaml
      inline_keyboard: !include command_list_keyboard.yaml
