alias: notify when cleaning started
trigger:
  platform: state
  entity_id: vacuum.xiaomi_vacuum_cleaner
  to: 'docked'
action:
  - service: telegram_bot.send_message
    data:
      message: 🤖 Docked
