alias: notify when returning to the dock after idle
trigger:
  platform: state
  entity_id: vacuum.xiaomi_vacuum_cleaner
  from:
    - 'idle'
    - 'paused'
    - 'error'
  to: 'returning'
action:
  - service: telegram_bot.send_message
    data:
      target:
        - !secret telegram_chat_id_admin
        - !secret telegram_chat_id_ksenia
      message: 🤖 Going back to the dock
