homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Minsk
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 30
  external_url: !secret base_url

default_config:

cloud: false
script: !include config/scripts.yaml
automation: !include_dir_list config/automations
logger:
  default: info

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 50

vacuum:
  - platform: xiaomi_miio
    host: 192.168.100.8
    token: !secret vacuum_token

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_bot
    parse_mode: html
    trusted_networks:
      - 149.154.160.0/20
      - 91.108.4.0/22
      - 127.0.0.1
    allowed_chat_ids:
      - !secret telegram_chat_id_admin
      - !secret telegram_chat_id_ksenia
      - !secret telegram_chat_id_group

#notify:
#  - platform: telegram
#    name: telegram_group
#    chat_id: !secret telegram_chat_id_group
