alias: cleanup whole apartment on mon, thu at 12:00
trigger:
  platform: time
  at: '12:00:00'
condition:
  condition: time
  weekday:
    - mon
    - thu
action:
  - service: telegram_bot.send_message
    data:
      message: Starting scheduled cleanup of the whole apartment...
  - service: vacuum.start
    entity_id: vacuum.xiaomi_vacuum_cleaner
