alias: cleanup whole apartment on mon, wed, fri at 12:00
trigger:
  platform: time
  at: '12:00:00'
condition:
  condition: time
  weekday:
    - mon
    - wed
    - fri
action:
  - service: vacuum.start
    entity_id: vacuum.xiaomi_vacuum_cleaner
  - service: telegram_bot.send_message
    data:
      title: '🤖 <b>Cleanup started!</b>'
      message: Cleanup of the whole apartment has started
