- !include automations/cleanup_whole_apartment.yaml
- !include automations/updater.new_update.yaml

- !include automations/telegram/command_list.yaml

- !include automations/hass/start.yaml
- !include automations/hass/shutdown.yaml
- !include automations/hass/telegram/callback_hass.yaml
- !include automations/hass/telegram/callback_hass_restart.yaml

- !include automations/vacuum/cleaning.yaml
- !include automations/vacuum/docked.yaml
- !include automations/vacuum/error.yaml
- !include automations/vacuum/idle.yaml
- !include automations/vacuum/paused.yaml
- !include automations/vacuum/returning_from_cleaning.yaml
- !include automations/vacuum/returning_from_idle.yaml
- !include automations/vacuum/telegram/callback_vaccum.yaml
- !include automations/vacuum/telegram/callback_vacuum_cancel_cleanup.yaml
- !include automations/vacuum/telegram/callback_vacuum_clean_hall.yaml
- !include automations/vacuum/telegram/callback_vacuum_clean_kitchen.yaml
- !include automations/vacuum/telegram/callback_vacuum_clean_living_room.yaml
- !include automations/vacuum/telegram/callback_vacuum_dock.yaml
- !include automations/vacuum/telegram/callback_vacuum_start.yaml
- !include automations/vacuum/telegram/callback_vacuum_stop.yaml
