- alias: cleanup whole apartment on mon, wed, fri at 12:00
  trigger:
    platform: time
    at: '12:00:00'
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ now().weekday() == 0 }}'
      - condition: template
        value_template: '{{ now().weekday() == 2 }}'
      - condition: template
        value_template: '{{ now().weekday() == 4 }}'
  action:
    - service: vacuum.start
      entity_id: vacuum.xiaomi_vacuum_cleaner

    - service: telegram_bot.send_message
      data:
        title: '🤖 <b>Cleanup started!</b>'
        message: Cleanup of the whole apartment has started.
        parse_mode: html

- alias: start telegram conversation
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/start'
  action:
    - service: telegram_bot.send_message
      data:
        message: 'commands'
        inline-keyboard:
          - '/ping, /alarm'
          - '/siren'

- alias: notify when new update is available
  trigger:
    platform: state
    entity_id: updater.updater
    from: 'off'
    to: 'on'
  action:
    service: telegram_bot.send_message
    data:
      title: '<b>Update available!</b>'
      message: New version of Home Assistant <b>{{ state_attr('binary_sensor.updater', 'newest_version') }}</b> is now available.
      parse_mode: html
