- !include automations/cleanup_whole_apartment.yaml
- !include automations/updater.new_update.yaml
- !include automations/homeassistant.start.yaml
- !include automations/homeassistant.shutdown.yaml

- !include automations/telegram/command_list.yaml
- !include automations/telegram/callback_vaccum.yaml
- !include automations/telegram/callback_clean_hall.yaml
- !include automations/telegram/callback_hass.yaml
- !include automations/telegram/callback_hass_restart.yaml
