homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Minsk

http:
  base_url: !secret base_url

default_config:

cloud: false
script: !include scripts.yaml
automation: !include automations.yaml
google_assistant: !include google-assistant.yaml

vacuum:
  - platform: xiaomi_miio
    host: 192.168.100.8
    token: !secret vacuum_token

telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_bot
    parse_mode: html
    trusted_networks:
      - 149.154.160.0/20
      - 91.108.4.0/22
      - 127.0.0.1
    allowed_chat_ids:
      - !secret telegram_chat_id_admin
