homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Minsk

default_config:

cloud: false
script: !include scripts.yaml
automation: !include automations.yaml
google_assistant: !include google-assistant.yaml

vacuum:
  - platform: xiaomi_miio
    host: 192.168.100.8
    token: 6e416363415a4933504351516b725951
