homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Minsk

default_config:

cloud: false
script: !include scripts.yaml
automation: !include automations.yaml
google_assistant: !include google-assistant.yaml

vacuum:
  - platform: xiaomi_miio
    host: 192.168.100.8
    token: !secret vacuum_token

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot
    allowed_chat_ids:
      - !secret telegram_chat_id_admin
