homeassistant:
  name: Home
  unit_system: metric

default_config:

cloud: false
script: !include scripts.yaml
google_assistant: !include google-assistant.yaml

vacuum:
  - platform: xiaomi_miio
    host: 192.168.100.8
    token: 6e416363415a4933504351516b725951
