cleanup_kitchen:
  alias: cleanup kitchen
  description: Script to automate cleanup of the kitchen
  sequence:
    - service: xiaomi_miio.vacuum_clean_zone
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        repeats: 1
        zone:
          - [25000, 24400, 28700, 27200]

cleanup_hall:
  alias: cleanup hall
  description: Script to automate cleanup of the hall
  sequence:
    - service: xiaomi_miio.vacuum_clean_zone
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        repeats: 1
        zone:
          - [26000, 24400, 27800, 25300]
          - [26300, 22500, 28100, 24400]

cleanup_living_room:
  alias: cleanup living room
  description: Script to automate cleanup of the living room
  sequence:
    - service: xiaomi_miio.vacuum_clean_zone
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        repeats: 1
        zone:
          - [25000, 27300, 30500, 30700]

goto_target:
  alias: goto target
  description: Example of goto target command for vacuum
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_goto_target
        params: [26500, 25500]
