cleanup_hall:
  alias: cleanup hall
  description: Script to automate cleanup of the hall
  sequence:
    - service: xiaomi_miio.vacuum_clean_zone
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        repeats: 1
        zone:
          - [26000, 24400, 27800, 25200]
          - [26400, 22600, 28100, 24400]

goto_target:
  alias: goto target
  description: Example of goto target command for vacuum
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        command: app_goto_target
        params: [26500, 25500]
