alias: cleanup hall
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/vacuum_clean_hall'
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: Working on it...
  - service: telegram_bot.send_message
    data:
      message: Starting hall cleanup...
  - service: script.cleanup_hall
