alias: cleanup hall
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/vacuum_clean_kitchen'
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: Working on it...
  - service: telegram_bot.edit_message
    data:
      message_id: "last"
      chat_id: "{{ trigger.event.data.chat_id }}"
      message: Starting kitchen cleanup...
  - service: script.cleanup_kitchen
