alias: cleanup hall
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/vacuum_clean_living_room'
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: Working on it...
  - service: script.cleanup_living_room
  - service: telegram_bot.send_message
    data:
      title: '🤖 <b>Cleanup started!</b>'
      message: Cleanup of the living room has started
