alias: go to the dock
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/vacuum_dock'
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: returning...
  - service: vacuum.return_to_base
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
