alias: cancel current cleanup and return to base
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/vacuum_cancel_cleanup'
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: cancelling...
  - service: vacuum.stop
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
  - service: vacuum.return_to_base
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
