alias: list vacuum telegram commands
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/vacuum'
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: Working on it...
  - service: telegram_bot.edit_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
      message: 'Here are Vacuum commands:'
      inline_keyboard:
        - 'start:/vacuum_start'
        - 'hall:/vacuum_clean_hall, area1:/vacuum_clean_area1'
        - 'cancel:/vacuum_cancel_cleanup, stop:/vacuum_stop, dock:/vacuum_dock'
        - 'back:/vacuum_back'
