alias: stop current cleanup
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/vacuum_stop'
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: stopping...
  - service: vacuum.stop
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
