alias: list vacuum telegram commands
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/vacuum'
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: Working on it...
  - service: telegram_bot.edit_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
      message: 'Here are Vacuum commands:'
      inline_keyboard:
        - 'Start:/vacuum_start'
        - 'Clean kitchen:/vacuum_clean_kitchen, Clean hall:/vacuum_clean_hall, Clean living room:/vacuum_clean_living_room'
        - 'Cancel cleanup:/vacuum_cancel_cleanup, Stop:/vacuum_stop, Dock:/vacuum_dock'
