alias: list hass telegram commands
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/hass'
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: Working on it...
  - service: telegram_bot.edit_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: '{{ trigger.event.data.chat_id }}'
      message: 'Here are Home Assistant commands:'
      inline_keyboard:
        - 'restart:/hass_restart'
        - 'back:/hass_back'
