alias: back from hass commands to root commands
trigger:
  platform: event
  event_type: telegram_callback
  event_data:
    data: '/hass_back'
action:
  - service: telegram_bot.answer_callback_query
    data_template:
      callback_query_id: '{{ trigger.event.data.id }}'
      message: Working on it...
  - service: telegram_bot.edit_message
    data_template:
      message_id: '{{ trigger.event.data.message.message_id }}'
      chat_id: "{{ trigger.event.data.chat_id }}"
      message: 'Here are all available commands:'
      inline_keyboard:
        - 'vacuum:/vacuum'
        - 'hass:/hass'
