on:
  push:
    branches:
      - master

jobs:
  job1:
    name: Deploy home-assistant config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy config to server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HASS_SERVER_SSH_HOST }}
          port: ${{ secrets.HASS_SERVER_SSH_PORT }}
          username: ${{ secrets.HASS_SERVER_USER }}
          privateKey: ${{ secrets.HASS_SERVER_KEY }}
          local: config
          remote: hass/config

      - name: Deploy helper scripts to server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HASS_SERVER_SSH_HOST }}
          port: ${{ secrets.HASS_SERVER_SSH_PORT }}
          username: ${{ secrets.HASS_SERVER_USER }}
          privateKey: ${{ secrets.HASS_SERVER_KEY }}
          local: .
          remote: hass
          recursive: false
