name: Config deployment

on:
  push:
    branches:
      - master

jobs:
  job1:
    name: Deploy home-assistant config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy config to server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HASS_SERVER_SSH_HOST }}
          port: ${{ secrets.HASS_SERVER_SSH_PORT }}
          username: ${{ secrets.HASS_SERVER_USER }}
          privateKey: ${{ secrets.HASS_SERVER_KEY }}
          local: config
          remote: hass/config
          rmRemote: true

      - name: Deploy root config to server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HASS_SERVER_SSH_HOST }}
          port: ${{ secrets.HASS_SERVER_SSH_PORT }}
          username: ${{ secrets.HASS_SERVER_USER }}
          privateKey: ${{ secrets.HASS_SERVER_KEY }}
          local: ./configuration.yaml
          remote: hass

      - name: Deploy helper scripts to server
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.HASS_SERVER_SSH_HOST }}
          port: ${{ secrets.HASS_SERVER_SSH_PORT }}
          username: ${{ secrets.HASS_SERVER_USER }}
          privateKey: ${{ secrets.HASS_SERVER_KEY }}
          local: scripts
          remote: hass
          recursive: false

      - name: Notify admin about deployment
        uses: appleboy/telegram-action@0.0.7
        with:
          to: ${{secrets.TELEGRAM_ADMIN_CHAT_ID}}
          token: ${{secrets.TELEGRAM_BOT_TOKEN}}
          message: |
            🚀 <b>Changes deployed!</b>
            The latest changes have been deployed to the server.
            Restart is required in order to apply them
          format: html
