name: Hass server availability

on:
  push:
  schedule:
    - cron:  '0 * * * *'

jobs:
  job1:
    name: Verify hass server is available
    runs-on: ubuntu-latest
    steps:
      - id: ping_step
        name: Ping server
        shell: bash
        run: |
          status=`curl -o /dev/null -s -w "%{http_code}\n" \
                        -H "Authorization: Bearer ${{secrets.HASS_TOKEN}}" \
                        ${{secrets.HASS_ADDRESS}}/api/config`

          if [[ $status != 200 ]]; then
            exit 1
          fi

      - name: Notify admin that server is down
        if: ${{ failure() }}
        uses: appleboy/telegram-action@0.0.7
        with:
          to: ${{secrets.TELEGRAM_ADMIN_CHAT_ID}}
          token: ${{secrets.TELEGRAM_BOT_TOKEN}}
          message: |
            ❗️ <b>Server is down!</b>
            Home assistant server is not available
          format: html
